# .github/workflows/freebsd-release.yml
name: Build FreeBSD amd64 Release

on:
  push:
    tags:
      - 'v*'   # 只有打 tag 时才触发
  workflow_dispatch:  # 也可以手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'  

      - name: Build FreeBSD amd64 binary
        run: |
          mkdir -p dist
          GOOS=freebsd GOARCH=amd64 go build -o dist/hubproxy-freebsd-amd64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hubproxy-freebsd-amd64
          path: dist/hubproxy-freebsd-amd64

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/hubproxy-freebsd-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
